GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/3

###
DELETE http://localhost:3001/api/persons/16594

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Gigel",
    "number": "0736724153"
}
